spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  application:
    name: ORDER-SERVICE

server:
  port: 8081

mapstruct:
  defaultComponentModel=spring:

  # FEIGN PRODUCT

feign:
  client:
    config:
      product:
        url: http://localhost:8080/product