spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  application:
    name: ORDER-SERVICE

server:
  port: 8081

mapstruct:
  defaultComponentModel=spring:

  # FEIGN PRODUCT

feign:
  client:
    config:
      product:
        url: ${HOST_PRODUCT_SERVICE}
      payment:
        url: ${HOST_PAYMENT}