spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: data.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration